apiVersion: v1
kind: Service
metadata:
  name: svc-example
spec:
  type: NodePort
  selector:
    app: nginx
    env: prod
  ports:
    - protocol: TCP
      nodePort: 32000 # port on the node
      port: 80 # port on the service
      targetPort: 80 # port on the pod