apiVersion: v1
kind: Pod
metadata:
  name: mybox
spec:
  restartPolicy: Always
  containers:
  - name: mybox
    image: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh", "-c", "while true; do echo hello; sleep 10;done"]
    env:
    - name: CITY
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: city