apiVersion: v1
kind: Service
metadata:
  name: svc-example
spec:
  type: ClusterIP # default value
  ports:
  - port: 8080 # port on the service
    targetPort: 80 # port on the pod
  selector:
    app: app-example
