apiVersion: apps/v1
kind: Deployment
metadata:
  name: myngnix
  labels:
    app: ngnix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngnix
      env: prod
  template:
    metadata:
      labels:
        app: ngnix
        env: prod
    spec:
      containers:
      - name: ngnix
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80