apiVersion: v1
kind: Service
metadata:
  name: svc-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: prod
  ports:
  - protocol: TCP
    port: 8080 # port on the service
    targetPort: 80 # port on the pod